name: DegNet_CLIP_Classification
seed: 42

experiments_dir: /home/yhmi/data/experiments

data:
  split_val: true # no provide val dataset, spilt from train data.  
  val_split: 0.2
  degradations: ['Blur', 'Noise', 'JPEG', 'Haze', 'Rain', 'Lowlight']
  
  dataloader:
    use_shuffle: true
    train:
      batch_size: 256
      num_workers: 16

    val:
      batch_size: 1
      num_workers: 4
  
  datasets:
    TrainDataset1: 
      name: Blur
      degradation: Blur
      path: /home/yhmi/data/Datadir/FoundIR/01Blur/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
    
    TrainDataset2:
      name: Rain
      degradation: Rain
      path: /home/yhmi/data/Datadir/FoundIR/10Rain/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
      
    TrainDataset3:
      name: Haze
      degradation: Haze
      path: /home/yhmi/data/Datadir/FoundIR/08Haze/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
      
    TrainDataset4:
      name: Lowlight
      degradation: Lowlight
      path: /home/yhmi/data/Datadir/FoundIR/14Lowlight/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
      
    TrainDataset5:
      name: Noise
      degradation: Noise
      path: /home/yhmi/data/Datadir/FoundIR/05Noise/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
      
    TrainDataset6:
      name: JPEG
      degradation: JPEG
      path: /home/yhmi/data/Datadir/FoundIR/06JPEG/LQ
      resize: 224
      use_hflip: true
      #use_rot: true
  
  # if provide val dataset, set spilt_val: false

network:
  type: DegNet_CLIP       
  backbone: /home/yhmi/data/model/clip-vit-base-patch32
  feature_dim: 512
  num_classes: 6 # len of Degradations
  freeze_encoder: False

train:
  num_epochs: 10
  mixed_precision: "bf16" # "no", "fp16", "bf16"
  gradient_accumulation_steps: 4

  optim:
    type: AdamW
    lr: 1e-4
    weight_decay: 0.01
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 20
    eta_min: 1e-6
  
  loss:
    type: BCEWithLogitsLoss
    loss_weight: !!float 1.0

  weight_save_best: true
  warmup_iter: -1 # no warm up

val:
  val_freq: 1 # epoch
  save_img: false
  metrics:
    type: accuracy

logging:
  use_swanlab: true
  swanlab_project: "Train_FoundIR_MultiLabel_DegNetCLIP"
  log_interval: 10

find_unused_parameters: True
