name: DegNet_CLIP_Classification
seed: 42
experiments_dir: /home/yhmi/data/experiments

accelerator:
  mixed_precision: "no" # "no", "fp16", "bf16"
  find_unused_parameters: False

data:
  degradations: ['Blur', 'Noise', 'Clean', 'Haze', 'Rain', 'Lowlight']

  dataloader:
    train:
      batch_size: 256
      num_workers: 12
      pin_memory: true
      persistent_workers: true
      drop_last: false
      prefetch_factor: 2

    val:
      batch_size: 256
      num_workers: 8
      pin_memory: true
      persistent_workers: true
      drop_last: false
      prefetch_factor: 2
  
  datasets:
    TrainDataset1: 
      name: Blur
      degradation: Blur
      path: /home/yhmi/data/Datadir/FoundIR_768/01Blur/LQ_train
      resize: 224
      #use_hflip: true
      #use_rot: true
    
    TrainDataset2:
      name: Rain
      degradation: Rain
      path: /home/yhmi/data/Datadir/FoundIR_768/10Rain/LQ_train
      resize: 224
      #use_hflip: true
      #use_rot: true
      
    TrainDataset3:
      name: Haze
      degradation: Haze
      path: /home/yhmi/data/Datadir/FoundIR_768/08Haze/LQ_train
      resize: 224
      #use_hflip: true
      #use_rot: true
      
    TrainDataset4:
      name: Lowlight
      degradation: Lowlight
      path: /home/yhmi/data/Datadir/FoundIR_768/14Lowlight/LQ_train
      resize: 224
      #use_hflip: true
      #use_rot: true
      
    TrainDataset5:
      name: Noise
      degradation: Noise
      path: /home/yhmi/data/Datadir/FoundIR_768/05Noise/LQ_train
      resize: 224
      #use_hflip: true
      #use_rot: true
      
    TrainDataset6:
      name: Clean
      degradation: Clean
      path: /home/yhmi/data/Datadir/FoundIR_768/01Blur/GT
      resize: 224
      #use_hflip: true
      #use_rot: true

    TrainDataset7:
      name: Blur_Noise
      degradation: [Blur, Noise]
      path: /home/yhmi/data/Datadir/FoundIR_768/02Blur_Noise/LQ_train
      resize: 224

    TrainDataset8:
      name: Lowlight_Haze
      degradation: [Lowlight, Haze]
      path: /home/yhmi/data/Datadir/FoundIR_768/09Lowlight_Haze/LQ_train
      resize: 224

    TrainDataset9:
      name: Rain_Haze
      degradation: [Rain, Haze]
      path: /home/yhmi/data/Datadir/FoundIR_768/13Rain_Haze/LQ_train
      resize: 224

    TrainDataset10:
      name: Lowlight_Blur
      degradation: [Lowlight, Blur]
      path: /home/yhmi/data/Datadir/FoundIR_768/15Lowlight_Blur/LQ_train
      resize: 224

    TrainDataset11:
      name: Lowlight_Noise
      degradation: [Lowlight, Noise]
      path: /home/yhmi/data/Datadir/FoundIR_768/16Lowlight_Noise/LQ_train
      resize: 224

    ValDataset1:
      name: Blur
      degradation: Blur
      path: /home/yhmi/data/Datadir/FoundIR_768/01Blur/LQ_val
      resize: 224

    ValDataset2:
      name: Rain
      degradation: Rain
      path: /home/yhmi/data/Datadir/FoundIR_768/10Rain/LQ_val
      resize: 224

    ValDataset3:
      name: Haze
      degradation: Haze
      path: /home/yhmi/data/Datadir/FoundIR_768/08Haze/LQ_val
      resize: 224

    ValDataset4:
      name: Lowlight
      degradation: Lowlight
      path: /home/yhmi/data/Datadir/FoundIR_768/14Lowlight/LQ_val
      resize: 224

    ValDataset5:
      name: Noise
      degradation: Noise
      path: /home/yhmi/data/Datadir/FoundIR_768/05Noise/LQ_val
      resize: 224

    ValDataset6:
      name: Clean
      degradation: Clean
      path: /home/yhmi/data/Datadir/FoundIR_768/01Blur/GT
      resize: 224

    # Second-order validation datasets
    ValDataset7:
      name: Blur_Noise
      degradation: [Blur, Noise]
      path: /home/yhmi/data/Datadir/FoundIR_768/02Blur_Noise/LQ_val
      resize: 224

    ValDataset8:
      name: Lowlight_Haze
      degradation: [Lowlight, Haze]
      path: /home/yhmi/data/Datadir/FoundIR_768/09Lowlight_Haze/LQ_val
      resize: 224

    ValDataset9:
      name: Rain_Haze
      degradation: [Rain, Haze]
      path: /home/yhmi/data/Datadir/FoundIR_768/13Rain_Haze/LQ_val
      resize: 224

    ValDataset10:
      name: Lowlight_Blur
      degradation: [Lowlight, Blur]
      path: /home/yhmi/data/Datadir/FoundIR_768/15Lowlight_Blur/LQ_val
      resize: 224

    ValDataset11:
      name: Lowlight_Noise
      degradation: [Lowlight, Noise]
      path: /home/yhmi/data/Datadir/FoundIR_768/16Lowlight_Noise/LQ_val
      resize: 224
  
network:
  type: DegNet_CLIP       
  backbone: /home/yhmi/data/model/clip-vit-base-patch32
  feature_dim: 512
  num_classes: 6 # len of Degradations
  freeze_encoder: False

train:
  num_epochs: 10
  max_grad_norm: 1.0
  
  optim:
    type: AdamW
    lr: 1e-4
    weight_decay: 0.01
  
  scheduler:
    eta_min: 1e-6

  loss:
    type: MultiLabelFocalLoss
    gamma: 2.0
    alpha: null
    label_smoothing: 0.0

val:
  val_freq: 1

logging:
  use_swanlab: true
  swanlab_project: "Train_FoundIR_MultiLabel_DegNetCLIP"
  log_interval: 10
