# general settings
name: DegNetCLIP_FoundIR_MultiLabel_Classification
model_type: DegNet
scale: 1
num_gpu: auto
manual_seed: 0
classify: true

datasets:
  train_01Blur:
    name: Blur
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/01Blur/LQ_train
    io_backend:
      type: disk 
    gt_size: 224
    use_hflip: true
    use_rot: false  
    label: [1, 0, 0, 0, 0, 0]
  
  val_01Blur:
    name: Blur
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/01Blur/LQ_val
    io_backend:
      type: disk 
    gt_size: 224
    use_hflip: false
    use_rot: false  
    label: [1, 0, 0, 0, 0, 0]
  
  train_05Noise:
    name: Noise
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/05Noise/LQ_train
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: false
    label: [0, 1, 0, 0, 0, 0]

  val_05Noise:
    name: Noise
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/05Noise/LQ_val
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: false
    use_rot: false
    label: [0, 1, 0, 0, 0, 0]

  train_06JPEG:
    name: JPEG
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/06JPEG/LQ_train
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: false
    label: [0, 0, 1, 0, 0, 0]

  val_06JPEG:
    name: JPEG
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/06JPEG/LQ_val
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: false
    use_rot: false
    label: [0, 0, 1, 0, 0, 0]

  train_08Haze:
    name: Haze
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/08Haze/LQ_train
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: false
    label: [0, 0, 0, 1, 0, 0]

  val_08Haze:
    name: Haze
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/08Haze/LQ_val
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: false
    use_rot: false
    label: [0, 0, 0, 1, 0, 0]

  train_10Rain:
    name: Rain
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/10Rain/LQ_train
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: false
    label: [0, 0, 0, 0, 1, 0]

  val_10Rain:
    name: Rain
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/10Rain/LQ_val
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: false
    use_rot: false
    label: [0, 0, 0, 0, 1, 0]

  train_14Lowlight:
    name: Lowlight
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/14Lowlight/LQ_train
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: false
    label: [0, 0, 0, 0, 0, 1]

  val_14Lowlight:
    name: Lowlight
    type: SingleImageClassificationDataset
    dataroot_lq: /home/yhmi/data/Datadir/FoundIR/14Lowlight/LQ_val
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: false
    use_rot: false
    label: [0, 0, 0, 0, 0, 1]

dataloader:
  phase: train
  use_shuffle: true
  
  num_worker_per_gpu: 32
  batch_size_per_gpu: 256
  dataset_enlarge_ratio: 10
  
  prefetch_mode: cuda
  pin_memory: true
  presist_workers: true

dataloader_val:
  phase: val
  use_shuffle: false
  num_worker_per_gpu: 4
  batch_size_per_gpu: 32

find_unused_parameters: false

network_dc:
  type: DegNet_CLIP
  num_types: 6  # ['Blur', 'Noise', 'JPEG', 'Haze', 'Rain', 'Lowlight']
  feature_dim: 512
  encoder_type: /home/yhmi/data/model/clip-vit-base-patch32
  freeze_encoder: false

path:
  resume_state: ~

train:
  ema_decay: 0.999
  optim_dc:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000,100000]
    restart_weights: [1,1]
    eta_min: !!float 1e-6
  
  total_iter: 200000
  warmup_iter: -1

  classify_opt:
    type: BCEWithLogitsLoss

val:
  val_freq: !!float 5000
  save_img: false
  metrics: ~

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_swanlab: true
  use_tb_logger: false
  swanlab_project: "DegNet_CLIP_FoundIR_Classification"
  swanlab_run_name: "degnet_clip_baseline"
  log_interval: 100
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500