name: DegNet_CLIP_Classification_CDD11
seed: 42
experiments_dir: /home/yhmi/data/experiments

logging:
  swanlab_project: "Train_CDD_MultiLabel_DegNetCLIP"
  log_interval: 100

accelerator:
  mixed_precision: "bf16"
  grad_accum: 1
  find_unused_parameters: false

data:
  degradations: ['Snow', 'Haze', 'Rain', 'Lowlight']
  split_val: true
  val_split: 0.2

  dataloader:
    use_shuffle: true
    train:
      batch_size: 1024
      num_workers: 16
      pin_memory: true
      persistent_workers: true
      drop_last: true

    val:
      batch_size: 1
      num_workers: 4
      pin_memory: true
      persistent_workers: true
      drop_last: true

  datasets:
    TrainDataset1:
      name: Rain
      degradation: Rain
      path: /home/yhmi/data/TrainData/CDD-11/CDD-11_train/rain
      resize: 224
      use_hflip: true

    TrainDataset2:
      name: Lowlight
      degradation: Lowlight
      path: /home/yhmi/data/TrainData/CDD-11/CDD-11_train/low
      resize: 224
      use_hflip: true

    TrainDataset3:
      name: Haze
      degradation: Haze
      path: /home/yhmi/data/TrainData/CDD-11/CDD-11_train/haze
      resize: 224
      use_hflip: true

    TrainDataset4:
      name: Snow
      degradation: Snow
      path: /home/yhmi/data/TrainData/CDD-11/CDD-11_train/snow
      resize: 224

network:
  type: DegNet_CLIP
  backbone: /home/yhmi/data/model/clip-vit-base-patch32
  feature_dim: 512
  num_classes: 4
  freeze_encoder: false

train:
  num_epochs: 10
  max_grad_norm: 1.0

  optim:
    type: AdamW
    lr: 1e-4
    weight_decay: 0.01

  scheduler:
    type: CosineAnnealingLR
    eta_min: 1e-6

  loss:
    type: BCEWithLogitsLoss

val:
  val_freq: 1
  save_img: false
  metrics: ["accuracy", "mAP", "F1"]
